### DISCUSSION TITLE
Using arrays parameters in Matrix

### DISCUSSION THREAD

**Discussion by cnd4** [tektoncd/catalog#1201] [Q&A]
Hello,

I'm trying to use `matrix` with the [kaniko task](https://hub.tekton.dev/tekton/task/kaniko) which takes an `EXTRA_ARGS` parameter (an array of string).

So here is my pipeline task:

```yaml
    - name: build
      runAfter: ["clone"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source-code
      params:
        - name: DOCKERFILE
          value: "Containerfile"
      matrix:
        params:
          - name: EXTRA_ARGS
            value:
              - ["--no-push", "--target production", "--build-arg MY_VAR=toto"]
```

I expect to get a generated YAML like:

```yaml
    - name: build
      runAfter: ["clone"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: source-code
      params:
        - name: DOCKERFILE
          value: "Containerfile"
        - name: EXTRA_ARGS
          value: ["--no-push", "--target", "production", "--build-arg", "MY_VAR=toto"]
```

But I guess it does not work because I get the following error with `tkn logs <pipelinerun-name>`:

```
parameters of type array only are allowed, but param EXTRA_ARGS has type string
```

Did I do something wrong when trying to use an array of arrays in `matrix.params.[].value`?

Thanks for any help!
