### DISCUSSION TITLE
Got-Clone container takes 30+ seconds to initialise

### DISCUSSION THREAD

**Discussion by BryanDollery** [tektoncd/catalog#941] [Q&A]
I have no idea why, but it is taking upwards of 30+ seconds to init my git-clone container. My pipeline has the following task:

```yaml
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name) 
```

And the relevant bits of the runner are:

```yaml
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - writeWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: git@github.com:<redacted>
  - name: branch-name
    value: feature/ctx/service-invoice
```

Any ideas why this might be happening, and how I can fix this? It's making my builds rather slow.
