### ISSUE TITLE
git-clone prepare container "will run as root"

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/catalog#1097]
# Description
I'm running Openshift-pipelines 1.8.0 which uses the following components:
- Tekton Pipelines: v0.37.4
- Tekton Triggers: v0.20.2
- Tekton Chains (tech-preview): v0.9.0
- Tekton Hub (tech-preview): v1.8.0
- Pipelines as Code (tech-preview): 0.10.2

I'm then using the git-clone v0.8 or v0.9 task whereby my pipelineRun contains the following securityContext:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: git-clone-
spec:
  pipelineRef:
    name: git-clone-pipeline
  taskRunSpecs:
    - pipelineTaskName: fetch-source
      taskServiceAccountName: pipelinenonroot
      taskPodTemplate:
        securityContext:
          fsGroup: 65532
...
```

And the task contains:
```
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
```

As per the settings here: https://hub.tekton.dev/tekton/Task/git-clone/0.8 (and here: https://hub.tekton.dev/tekton/Task/git-clone/0.9).

And the `pipelinenonroot` serviceAccount is only permitted to use the `nonroot` SCC:
```
oc get clusterrolebinding.rbac system:openshift:scc:nonroot -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:nonroot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:nonroot
subjects:
- kind: ServiceAccount
  name: pipelinenonroot
  namespace: tekton-pipelines
```

# Expected Behavior
Pipeline runs and the fetch-source task runs as the nonroot user `65532`. This worked fine when running v0.5 of the git-clone task and pipelineRun settings.

# Actual Behavior
My task never runs as my pod has this status ` Init:CreateContainerConfigError` and instead I get the following error when I `oc describe` my pod:
```
Error: container has runAsNonRoot and image will run as root (pod: "demo-syft-task-ncc4c-fetch-source-pod_tekton-pipelines(c939ead3-acd5-418d-bfc2-85029f931c4e)", container: prepare)
```

# Steps to Reproduce the Problem

1. Use the git-clone v0.8/0.9 configuration
2. Run on OpenShift-Pipelines 1.8.0
3. Specify the serviceAccountName for the task is one that does not have access to `anyuid` or other SCC allowing root user
4. Run pipeline

# Additional Info
This is the events I get from 0.8 or 0.9:
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m32s                  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  2m26s (x1 over 2m29s)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         56s                    default-scheduler  Successfully assigned tekton-pipelines/demo-syft-task-8xqlw-fetch-source-pod to 10.112.78.53
  Normal   AddedInterface    29s                    multus             Add eth0 [172.30.90.199/32] from k8s-pod-network
  Normal   Pulled            12s (x4 over 28s)      kubelet            Container image "registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@sha256:5351b0d07e615643a1363b3c72949d1155bb75cd04b06072853dc07f46771444" already present on machine
  Warning  Failed            12s (x4 over 28s)      kubelet            Error: container has runAsNonRoot and image will run as root (pod: "demo-syft-task-8xqlw-fetch-source-pod_tekton-pipelines(cdfcd053-35dc-43c5-b6da-37889079471a)", container: prepare)
```

This is the events I get from 0.5:
```  
  Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  119m  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  118m  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         118m  default-scheduler  Successfully assigned tekton-pipelines/syft-pipeline-ppypgf-fetch-source-pod to 10.112.78.59
  Normal   AddedInterface    117m  multus             Add eth0 [172.30.244.27/32] from k8s-pod-network
  Normal   Pulled            117m  kubelet            Container image "registry.redhat.io/openshift-pipelines/pipelines-entrypoint-rhel8@sha256:5351b0d07e615643a1363b3c72949d1155bb75cd04b06072853dc07f46771444" already present on machine
  Normal   Created           117m  kubelet            Created container prepare
  Normal   Started           117m  kubelet            Started container prepare
  Normal   Pulled            117m  kubelet            Container image "registry.redhat.io/ubi8/ubi-minimal@sha256:c7b45019f4db32e536e69e102c4028b66bf5cde173cfff4ffd3281ccf7bb3863" already present on machine
  Normal   Created           117m  kubelet            Created container place-scripts
  Normal   Started           117m  kubelet            Started container place-scripts
  Normal   Pulling           117m  kubelet            Pulling image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.29.0"
  Normal   Pulled            117m  kubelet            Successfully pulled image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.29.0" in 18.4788277s
  Normal   Created           117m  kubelet            Created container step-clone
  Normal   Started           117m  kubelet            Started container step-clone
```
