### ISSUE TITLE
skopeo-copy task fails with error "Exactly two arguments expected".

### ISSUE THREAD

**Issue by dcommisso** [tektoncd/catalog#1117]
# Expected Behavior
skopeo-copy task [here](https://github.com/tektoncd/catalog/blob/main/task/skopeo-copy/0.2/skopeo-copy.yaml) properly works without errors
# Actual Behavior
skopeo-copy task fails with error `Exactly two arguments expected` when using multiple source and destination image registries.
# Steps to Reproduce the Problem

1. Create a file named `url.txt` containing all the source and destination image registries URL seperated by a space. Each set of images should be written in the new line.
2. Create a configmap using this file:
   ```
   kubectl create ConfigMap image-configmap --from-file=url.txt
   ```
3. Create a TaskRun referring the configmap:
   ```
   apiVersion: tekton.dev/v1beta1
   kind: TaskRun
   metadata:
     name: skopeo-run
   spec:
     serviceAccountName: secret-service-account
     taskRef:
       name: skopeo-copy
     workspaces:
     - name: images-url
       configmap:
         name: image-configmap
   ```

# Additional Info
The problem is the double quotes in `"$cmd"` [here](https://github.com/tektoncd/catalog/blob/bf905bd8664fe32c0e725acf48d2bf2eeaf28e39/task/skopeo-copy/0.2/skopeo-copy.yaml#L62)

The reason is that double quotes prevents word splitting and an argument enclosed in double quotes presents itself as a single word, even if it contains whitespace separators. Therefore skopeo gets just one argument and complains with the error message `Exactly two arguments expected`.

The solution is to remove the double quotes from `$cmd` parameter. I will open a PR to fix this.
