### ISSUE TITLE
git-clone permissions issues when workspace uses volumeClaimTemplate

### ISSUE THREAD

**Issue by adam-power** [tektoncd/catalog#1154]
# Expected Behavior

When I create a `Pipeline` and `PipelineRun` object referencing the git-clone resolver, I expect to be able to configure the `PipelineRun` to use a volumeClaimTemplate to back the "git-source" workspace, so I can pass the cloned Git repository to later tasks.

# Actual Behavior

During execution of the git-clone task, I get a permissions error because the task is running as the `git` user and the PVC mounted to /workspace/output/ is owned by `root`.

This is the full error:
```
Defaulted container "step-clone" out of: step-clone, prepare (init), place-scripts (init)
+ '[' false '=' true ]
+ '[' false '=' true ]
+ '[' false '=' true ]
+ CHECKOUT_DIR=/workspace/output/
+ '[' true '=' true ]
+ cleandir
+ '[' -d /workspace/output/ ]
+ rm -rf /workspace/output//lost+found
+ rm -rf '/workspace/output//.[!.]*'
+ rm -rf '/workspace/output//..?*'
+ test -z
+ test -z
+ test -z
+ git config --global --add safe.directory /workspace/output
+ /ko-app/git-init '-url=https://github.com/tektoncd/catalog.git' '-revision=main' '-refspec=' '-path=/workspace/output/' '-sslVerify=true' '-submodules=true' '-depth=1' '-sparseCheckoutDirectories='
{"level":"error","ts":1679929403.1163123,"caller":"git/git.go:53","msg":"Error running git [init /workspace/output/]: exit status 1\n/workspace/output/.git: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:88\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:250"}
{"level":"fatal","ts":1679929403.116427,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:250"}
```

# Steps to Reproduce the Problem

1. Create this `Pipeline`:
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-deploy-test
spec:
  params:
  - name: git-url
  - name: git-revision
  - name: file-path
  workspaces:
  - name: git-source
  tasks:
  - name: fetch-from-git
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/tektoncd/catalog.git
      - name: pathInRepo
        value: /task/git-clone/0.9/git-clone.yaml # not-working
        # value: /task/git-clone/0.7/git-clone.yaml # working
      - name: revision
        value: main
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: git-source
  - name: show-files
    runAfter: [fetch-from-git]
    taskRef:
      name: show-files
    workspaces:
    - name: git-repo
      workspace: git-source
    params:
    - name: file-path
      value: "$(params.file-path)"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-files
spec:
  params:
  - name: file-path
    description: Path to the files to show
  workspaces:
  - name: git-repo
  steps:
  - name: show-files
    workingDir: $(workspaces.git-repo.path)
    image: busybox:latest
    script: |
      #!/bin/sh

      set -x

      pwd
      ls -l $(params.file-path)
```

2. Create this `PipelineRun`:
```yaml
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: app-deploy-test
spec:
  pipelineRef:
    name: app-deploy-test
  params:
  - name: git-url
    value: https://github.com/tektoncd/catalog.git
  - name: git-revision
    value: main
  - name: file-path
    value: "./"
  workspaces:
  - name: git-source
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

# Additional Info

If you switch the above pipeline from 0.9 to 0.7, it successfully lists the files.  I believe this is because 0.7 and earlier versions ran as root, whereas 0.9 runs as the non-root `git` user.
