### ISSUE TITLE
Wget failing with Scheme missing

### ISSUE THREAD

**Issue by khrm** [tektoncd/catalog#1155]
# Expected Behavior
wget should download to filename given.
# Actual Behavior
```
[fetch-data : wget] --2023-04-04 01:02:34--  ht,....
[fetch-data : wget] Resolving api.npoint.io (api.npoint.io)... 216.24.57.253, 216.24.57.3
[fetch-data : wget] Connecting to api.npoint.io (api.npoint.io)|216.24.57.253|:443... connected.
[fetch-data : wget] HTTP request sent, awaiting response... 200 OK
[fetch-data : wget] Length: unspecified [application/json]
[fetch-data : wget] Saving to: 'e1ce697d6d9'
[fetch-data : wget] 
[fetch-data : wget]      0K                                                        27.7M=0s
[fetch-data : wget] 
[fetch-data : wget] 2023-04-04 01:02:35 (27.7 MB/s) - 'e1cea97d6d9' saved [274]
[fetch-data : wget] 
[fetch-data : wget] /workspace/wget-workspace/README.json: Scheme missing.
[fetch-data : wget] FINISHED --2023-04-04 01:02:35--
[fetch-data : wget] Total wall clock time: 1.0s
[fetch-data : wget] Downloaded: 1 files, 274 in 0s (27.7 MB/s)
```
# Steps to Reproduce the Problem

1.
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: "demo-pipeline"
spec:
  params:
    - name: filename
      type: string
      description: The name of the file to be created
    - name: transform-path
      type: string
      description: The path of the transformed file
    - name: url
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-data
      taskRef:
        name: wget
      workspaces:
        - name: wget-workspace
          workspace: shared-workspace
      params:
        - name: filename
          value: "$(params.filename)"
        - name: url
          value: "$(params.url)"
``` 
2. Create run
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: demo-pipeline-
spec:
  pipelineRef:
    name: "demo-pipeline"
  params:
    - name: filename
      value: README.json
    - name: url
      value: https://api.npoint.io/sample
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi


3.

# Additional Info
