### ISSUE TITLE
Error while using hadolint task

### ISSUE THREAD

**Issue by R3DRUN3** [tektoncd/catalog#1159]
# Expected Behavior
The task run without problems.
# Actual Behavior
The following error is presented:
```console
Error from server (BadRequest): error when creating "tekton/pipeline.yaml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: non-existent variable in "$(params.dockerfile-path)": spec.tasks[1].params[dockerfile-path]
non-existent variable in "$(params.ignore-rules)": spec.tasks[1].params[ignore-rules]
```
# Steps to Reproduce the Problem

This is my pipeline.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
#  - name: docker-credentials
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: docker-lint
    runAfter: ["fetch-source"]
    taskRef:
      kind: Task
      name: hadolint
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: ignore-rules
      value: $(params.ignore-rules)
    - name: dockerfile-path
      value: $(params.dockerfile-path)
  - name: build-push
    runAfter: ["docker-lint"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    # - name: dockerconfig
    #   workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference)
    - name: EXTRA_ARGS
      value: ["--insecure"]

```

and this is my pipelinerun.yaml:
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  # - name: docker-credentials
  #   secret:
  #     secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/stackzoo/simple-web-app.git
  - name: ignore-rules
    value: 'DL3007,DL3045,DL3042'
  - name: dockerfile-path
    value: './Dockerfile'
  - name: image-reference
    value: host.docker.internal:5000/app:latest

```

# Additional Info
If I remove the `ignore-rules` and `dockerfile-path` variables it works but the pipeline give linting warning and stops with error status.

**Comment by vdemeester** [comment]
@R3DRUN3 `dockerfile-path` and `ignore-rules` are missing from the `Pipeline` parameters in the spec.

```
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  - name: dockerfile-path
    type: string
  - name: ignore-rules
    type: string
```

This is not really related to the hadolint task at all, but it's consumption.
