### ISSUE TITLE
Superfluous 'output' workspace defined in git-cli env

### ISSUE THREAD

**Issue by the-it-jaeger** [tektoncd/catalog#1289]
https://github.com/tektoncd/catalog/blob/96c4ea272d13efceabc26626fe80f83e017b43d9/task/git-cli/0.4/git-cli.yaml#L105-L106

I see no reference to this workspace anywhere else, and it's causing my PipelineRun to fail with:

> expected workspace "output" to be provided by pipelinerun for pipeline task "update-image-tag"

Where the `update-image-tag` Task has `taskRef: git-cli`

I did not get the error with OpenShift Pipelines 1.14, but I _do_ with OpenShift Pipelines 1.15. Upstream Tekton version translations below.

|Operator | Pipelines | Triggers | CLI | Chains | Hub | Pipelines as Code | Results | Manual Approval Gate | OpenShift Version | Support Status |
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
1.15 | 0.59.x | 0.27.x | 0.37.x | 0.20.x (GA) | 1.17.x (TP) | 0.27.x (GA) | 0.10.x (TP) | 0.2.x (TP) | 4.14, 4.15, 4.16 | GA
1.14 | 0.56.x | 0.26.x | 0.35.x | 0.20.x (GA) | 1.16.x (TP) | 0.24.x (GA) | 0.9.x (TP) | NA | 4.12, 4.13, 4.14, 4.15, 4.16 | GA

**Comment by the-it-jaeger** [comment]
Adding a little 'output' workspace binding gets around this problem.

```
    - name: output
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Mi
```

Emptydir probably works just as well.
