### ISSUE TITLE
[buildah] Remove privileged: true by adding SETFCAP cap

### ISSUE THREAD

**Issue by jsalatiel** [tektoncd/catalog#1298]
The buildah task has `privileged: true` set in its pod securityContext

That can be replaced by
```
securityContext:
  capabilities:
     add:
     - SETFCAP
  ```
and the build will work without needing privileged which sometimes is not allowed in the cluster.

Tested in k8s 1.30 running crio 1.30
