### ISSUE TITLE
Cannot create step with script

### ISSUE THREAD

**Issue by raffamendes** [tektoncd/catalog#144]
I'm trying to create a step on a task that executes a script
```yaml
 - name: terraform-cli
      image: quay.io/rcmendes/terraform-cli:latest
      workingdir: /workspace/source
      script: |
            #!/usr/bin/env bash
            for f in * ; do echo "export $f=$(cat $f)" >> ~/.bashrc ; done
            source ~/.bashrc
            /usr/local/bin/terraform apply -auto-approve
      volumeMounts:
        - name: provider-credentials
          mountPath: "/workspace/source"
```

Getting the error message:
```
Internal error occurred: admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "script"
```

I'm Using CodeReadyContainers 4.2 and operator version 0.8
