### ISSUE TITLE
git-clone fails with results.commit.path: not found

### ISSUE THREAD

**Issue by holly-cummins** [tektoncd/catalog#228]
# Expected Behavior

I'm seeing unexpected errors in the execution of a git-clone task. 

# Actual Behavior

The task execution fails with the following error:
```
/tekton/scripts/script-0-xdcr2: line 40: results.commit.path: not found
/tekton/scripts/script-0-xdcr2: line 40: can't create : nonexistent directory
```
# Steps to Reproduce the Problem

This is the relevant snippet of my `pipeline.yml`:

```
    - name: pipeline-fetch-repository-task
      taskRef:
       name: git-clone
      params:
        - name: url
          value: $(params.repository)
        - name: subdirectory
          value: pipeline-checkout
      workspaces:
       - name: output
         workspace: shared-workspace  
```

# Additional Info

I've done a local workaround by commenting out line 40.
