### ISSUE TITLE
git-clone: some param values are inadvertently ignored

### ISSUE THREAD

**Issue by ryanewk** [tektoncd/catalog#275]
# Expected Behavior

Using the `git-clone` task, with the following params:

```yaml
- name: sslVerify
  value: "false"
- name: submodules
  value: "false"
- name: depth
  value: "2"
```

The task should not fail if the underlying git repository's https server is
using an untrusted self-signed certificate, it should not attempt to fetch
submodules, and it should fetch 2 commits.

# Actual Behavior

None of the above param values take effect - the default values are used.
The task will fail if there is an untrusted certificate in the chain. If it is a
trusted certificate, submodules will still be fetched and only a single commit
will be pulled.

# Steps to Reproduce the Problem

It is difficult to setup a repro for `sslVerify` but the underlying issue is the
same. The following will repro the issues with `submodules` and `depth`.

Assuming pipelines are installed and the git-clone Task exists, create the
following pipeline:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-log
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: subdirectory
      description: Subdirectory inside "source" workspace that contains the README.md.
      default: "."
  steps:
    - name: git-log
      image: alpine/git
      script: cd "$(workspaces.source.path)/$(params.subdirectory)"; git log --oneline
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: git-log-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: The git repo will be cloned into this workspace and git log will be run
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/tektoncd/pipeline.git
        - name: subdirectory
          value: pipeline-checkout
        - name: deleteExisting
          value: "true"
        - name: submodules
          value: "false"
        - name: depth
          value: "2"
    - name: git-log
      taskRef:
        name: git-log
      runAfter:
        - fetch-repository # required to ensure clone occurs before reading
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: subdirectory
          value: pipeline-checkout
```

And then run it with:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-log-pipeline-run
spec:
  pipelineRef:
    name: git-log-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace-pvc
```

In the logs for the `step-clone`, you will still see:

```sh
{"level":"info","ts":1586897972.7579875,"caller":"git/git.go:133","msg":"Successfully initialized and updated submodules in path /workspace/output/pipeline-checkout"}
...
```

And the `step-git-log` logs will show just a single commit:

```sh
git log --oneline
fe5981e Add volumeClaimTemplate as a Workspace volume source
```

# Additional Info

This appears to just be an issue with how the [bool and int flags](https://gist.github.com/ryanewk/eed221119a0b0366b0f13db5a587873a) are passed to git-init.
Right now, the command being executed looks like this:

```sh

/ko-app/git-init -url https://github.com/tektoncd/pipeline.git -revision master -path /workspace/output/pipeline-checkout -sslVerify=true -submodules=false -depth=2
```

If we change it to:

```sh
/ko-app/git-init -url https://github.com/tektoncd/pipeline.git -revision master -path /workspace/output/pipeline-checkout -sslVerify=true -submodules=false -depth=2
```

We get the expected behavior.
