### ISSUE TITLE
openshift-client task escapes single quotes

### ISSUE THREAD

**Issue by bgottfried91** [tektoncd/catalog#358]
The openshift-client ClusterTask is replacing single-quotes in the ARGS array parameter with escaped double quotes.

Ex: This task in a pipeline
```
  - name: prod-switch-route
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: ARGS
        value:
          - patch
          - -n $(params.GUID)-tasks-prod
          -  route tasks
          - -p '{"spec":{"to":{"name":"$(tasks.determine-dest-app.results.destApp)"}}}'
```
produces the following error when the pipeline is run:
```
[prod-switch-route : oc] + oc patch -n 1234-tasks-prod route tasks -p ''\''{"spec":{"to":{"name":"tasks-blue"}}}'\'''
[prod-switch-route : oc] Error from server (BadRequest): json: cannot unmarshal string into Go value of type map[string]interface {}
```

Note that the single quotes around the patch block are replaced with **"\"**.

I'm assuming this is something with how Tekton converts an array parameter into a single value.

If you do not provide the single quotes to wrap the patch block, the task will actually add them for you - if this is intended behavior, it would be good to call it out in the task README so that people know not to wrap in singlequotes.

# Steps to Reproduce the Problem

1. Run the openshift-client task using the ARGS parameter where one of the array values has single quotes in it

# Additional Info
    Kubernetes version:
    Openshift 4.4
    Output of kubectl version:
    oc v3.11.0+0cbc58b
    kubernetes v1.11.0+d4cacc0
    features: Basic-Auth GSSAPI Kerberos SPNEGO
    Server https://api.shared-dev4.dev4.openshift.opentlc.com:6443
    kubernetes v1.17.1

    Tekton Pipeline version:

    Output of tkn version or kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'
    v0.11.3
