### ISSUE TITLE
Create Tekton based Pipeline which has capability to run against multiple tekton pipelines versions

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/catalog#373]
# Expected Behavior

* Tasks should be able to declare what versions of Tekton Pipelines they are compatible with (https://github.com/tektoncd/pipeline/issues/2588)
* The catalog test infrastructure can use this information to determine what versions of Tekton Pipelines to test against

# Actual Behavior

All catalog Tasks are tested against 1 version of Tekton Pipelines, hard coded at https://github.com/tektoncd/catalog/blob/v1beta1/test/e2e-tests.sh#L19

# Additional Info

[Overall catalog test infrastructure proposal](https://docs.google.com/document/d/1-czjvjfpuIqYKsfkvZ5RxIbtoFNLTEtOxaZB71Aehdg/edit)

**Comment by chmouel** [comment]
That's a good idea, i can pick this up if you like.

I wonder what's is the best way to do this tho. Since pipeline supports does not support per namespace install.

Perhaps something like this : 

- Collect all pipeline versions of all tasks in catalog
- for each pipeline versions uninstall previous and install the new pipeline version.
- Run all catalog tasks that want that specifics version against it.

I think that's going to exponentially add a lot of time to each run. 

Perhaps we want to start to implement the feature to only test tasks that has been changed/added first?

**Comment by bobcatfish** [comment]
Hey @chmouel ! There's a sketch for how this could look [in the test infra design doc](https://docs.google.com/document/d/1-czjvjfpuIqYKsfkvZ5RxIbtoFNLTEtOxaZB71Aehdg/edit#heading=h.hzcpipuqmb1u) - i'm (slowly) working on a prototype, my biggest goal is to do this using tekton pipelines

> 1. Collect all pipeline versions of all tasks in catalog
> 2. for each pipeline versions, un-install the previous and install the new pipeline version.

For (2) I want to do that with a Pipeline that takes a version as an argument - also if we use boskos we can create multiple clusters and install whatever versions we want. If we use a completely separate GCP project for each one we're going to run out pretty quickly tho.

This is the psuedo pipeline code I've got so far:

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalog-test
spec:
  params:
    - name: pipelines-version
      default: "v0.13.2"
      description: The verision of tekton-pipelines to install and test with
    - name: task-paths
      description: A comma separated lists of the paths to the catalog tasks to test
  workspaces:
    - name: kubeconfig
    - name: project-creds
    - name: cluster-creds
  tasks:
    - name: get-project
      taskRef:
        name: boskos
      workspaces:
        - name: project-creds
          workspace: project-creds
    - name: make-cluster
      params:
        - name: project-name
          value: $(tasks.get-boskos-project.project-name)
      taskRef:
        name: tbd
      # Post https://github.com/tektoncd/pipeline/issues/1878 indicate workspace dependency instead
      runAfter: [get-project]
      workspaces:
        - name: kubeconfig
          workspace: kubeconfig
        - name: project-creds
          workspace: project-creds
        - name: cluster-creds
          workspace: cluster-creds
    - name: install-pipelines
      taskRef:
        name: kubectl
      # Post https://github.com/tektoncd/pipeline/issues/1878 indicate workspace dependency instead
      runAfter: [make-cluster]
      workspaces:
        - name: kubeconfig
          workspace: kubeconfig
        - name: creds
          workspace: cluster-creds
    - name: apply-tasks
      taskRef:
        name: kubectl
      runAfter: [install-pipelines]
      workspaces:
        - name: kubeconfig
          workspace: kubeconfig
        - name: creds
          workspace: cluster-creds
    - name: release-project
      taskRef:
        name: boskos
      workspaces:
        - name: project-creds
          workspace: project-creds
```

My next step is to start creating some of the individual tasks we'd need, e.g. the boskos task.
