### ISSUE TITLE
Add kubectl from path task

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/catalog#393]
# Expected Behavior
I'd love to be able to pick and choose tasks from the Tekton catalog for a demo/Twitch stream I'm planning with colleagues at iBM. Unfortunately the kubectl task I've found doesn't cut it - I want to simply do

```
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - '$(inputs.params.path)'
```

# Actual Behavior
The actual task has a pre-defined manifest that gets used and far too many required parameters.

# Additional Info
This shouldn't be tricky and hopefully that image isn't huge!

Update: @ImJasonH reports: `16 MB vs 681 MB` for the image size. 🥳
