### ISSUE TITLE
Validation Tool to follow the Catalog Structure

### ISSUE THREAD

**Issue by PuneetPunamiya** [tektoncd/catalog#413]
# Expected Behavior

1. Each resource should follow the following structure
```
    ./task/         👈 the kind of the resource 
      
      /argocd       👈 definition file must have same name
        /0.1
          /OWNERS     👈 owners of this ressource
          /README.md     
          /argocd.yaml   👈 the file name must be resource name
          /samples/deploy-to-k8s.yaml
        /0.2/...
     
     /golang-build
        /0.1
          /README.md
          /golang-build.yaml
          /samples/golang-build.yaml
```

* **NOTE** : The `resource name` and the `directory name` should match

2. Resource YAML file should include the following changes
  *  Labels include the version of the resource.
  *  Annotations include
     - `minimum pipeline version` supported by the resource 
     - `tags` associated with the resource
     - `displayName` of the resource
    
  ```yaml
    
 labels:
    app.kubernetes.io/version: "0.1"            👈 version of the resource
    
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"   👈 will work from x version  of pipeline
    tekton.dev/tags: "ansible, cli"                        👈 Comma separated list of tags 
    tekton.dev/displayName: "Ansible Tower Cli"  👈 displayName can be optional   
    
spec:
  description: |-
    ansible-tower-cli task simplifies 
    workflow, jobs, manage users...   👈 # Summary
    
    Ansible Tower (formerly ‘AWX’) is a ...
  
  ```

# Actual Behavior

  - API breakage 
  - No concept of versions
  - Are the Resources valid 
  - No field to mention Minimum Pipeline Version
