### ISSUE TITLE
Kaniko Task doesn't support GKE Workload Identity without hand edits

### ISSUE THREAD

**Issue by sbwsg** [tektoncd/catalog#448]
# Expected Behavior

Tasks should be able to support as many credential mechanisms as possible out of the box. For Kaniko this ideally means that it could support both a docker config file as it currently does as well as systems like GKE Workload Identity.

# Actual Behavior

As [reported in Slack here](https://tektoncd.slack.com/archives/CK3HBG7CM/p1595853519214500) Kaniko will stop looking for credentials if it sees a DOCKER_CONFIG environment variable defined.  This means that the catalog's kaniko Task disallows GKE Workdload Identity simply by virtue of [defining a DOCKER_CONFIG env var](https://github.com/tektoncd/catalog/blob/ec7c4f3836fe8ae4efd761e737e0b476a10c336d/task/kaniko/0.1/kaniko.yaml#L46).

**Comment by NavidZ** [comment]
I can also confirm the workaround worked. But what do you imagine the solution be on the Tekton part vs having a fix in Kaniko?
Would having this env conditional as part of the (task/pipeline)run that user defines work? So they can choose to pass or not pass it?

**Comment by sbwsg** [comment]
This is surprisingly tricky. Kaniko doesn't contain a shell by default and Tekton doesn't really support conditionally setting the environment variable. Parameterizing it would definitely be one approach - either the user would have to explicitly pass the path to the credential or we could add a param like "dontOverrideDockerConfig" (horrible name, just an example) to configure it.

One more alternative might be to start using the debug kaniko image and writing a script to detect the presence of the `/tekton/home/.docker` files? If they're empty or missing we could skip setting the env var. Something like this:

```yaml
# ... params
  - name: BUILDER_IMAGE
    description: The image on which builds will run
    default: gcr.io/kaniko-project/executor:debug # Note: debug image w/ shell
# ... 
  steps:
  - name: build-and-push
    workingDir: $(workspaces.source.path)
    image: $(params.BUILDER_IMAGE)
    script: |
      #!/busybox/sh
      if [[ -d "$HOME/.docker" ]] ; then
        export DOCKER_CONFIG="$HOME/.docker"
      fi
      /kaniko/executor $(params.EXTRA_ARGS) \
        --dockerfile=$(params.DOCKERFILE) \
        --context=$(workspaces.source.path)/$(params.CONTEXT) \
        --destination=$(params.IMAGE) \
        --oci-layout-path=$(workspaces.source.path)/$(params.CONTEXT)/image-digest
    securityContext:
      runAsUser: 0
```

This definitely seems to be going against the grain a little bit to call kaniko from a script but at least it might be "transparent" to the user?  I'm not sure which would be the best approach.
