### ISSUE TITLE
Doc enhancement : where git code is stored for s2i task

### ISSUE THREAD

**Issue by cmoulliard** [tektoncd/catalog#47]
## Doc enhancement

The s2i task of the catalog specifies a resource of type `git` without working dir. Is it possible to document where the project cloned is stored within the pod's task. Is it under the current path of the volume mounted ? Is it somewhere else ? Is it by default under `/workspace/` as reported within the git container log ?
 
That could be great to document that otherwise it is very difficult, hard to figure out how the first step of the build should be defined in order to use the files of the git cloned project

Example as defined within the s2i task - Git Resource
```
    resources:
     - name: source
       type: git
```

and steps
```
  steps:
  - name: generate
    image: quay.io/openshift-pipeline/s2i
    workingdir: /workspace/source
...
```
