### ISSUE TITLE
Ability to specify secret name and key in github tasks

### ISSUE THREAD

**Issue by Divyansh42** [tektoncd/catalog#555]
# Expected Behavior
Rather than forcing task users to create a secret with a fixed
name, allow setting the secret name and key as parameter.

The new parameters will be optional, in the sense that they default
to the previous hard-coded values.

Check [this](https://github.com/tektoncd/catalog/blob/master/task/github-set-status/0.2/github-set-status.yaml#L88-L90) for the same.
# Actual Behavior
Presently in few of the tasks we force the user to create a secret with a fixed name.
```
env:
    - name: GITHUBTOKEN
      valueFrom:
        secretKeyRef:
          name: github
          key: token
```
