### ISSUE TITLE
Feature request: New task for JFrog Artifactory

### ISSUE THREAD

**Issue by marcosflobo** [tektoncd/catalog#557]
# Feature Request
JFrog Artifactory is a very popular repository manager to store any kind of builds, from RPMs to Docker images. URL https://jfrog.com/artifactory/

It would be great to implement a task able to upload artifacts generated in a previous task

/kind feature

**Comment by tnixa** [comment]
i was able to build and push to artifactory by creating a secret:
```
oc create secret docker-registry <secret name> --docker-server=<URL to your artifactory registry> --docker-username=<artifactory username> --docker-password=<artifactory api key> --docker-email=<email address>
```
and then used this task:
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image.
      type: string
      default: registry.redhat.io/rhel8/buildah      
    - name: DOCKERFILE      
      description: Path to the Dockerfile to build.
      type: string
      default: ./Dockerfile      
    - name: CONTEXT
      description: Path to the directory to use as context.
      type: string
      default: .      
    - name: TLSVERIFY
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      type: string
      default: 'true'      
    - name: FORMAT
      description: 'The format of the built container, oci or docker'
      type: string
      default: oci      
    - name: IMAGENAME
      description: 'The name of the build image'
      type: string
      default: $(resources.outputs.image.url)
  workspaces:
  - name: output
    mountpath: /workdir
    description: The git repo will be cloned onto the volume backing this workspace  
  steps:
    - name: build
      image: $(params.BUILDER_IMAGE)
      command:
        - buildah
        - bud
        - '--format=$(params.FORMAT)'
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--layers'
        - '-f'
        - $(params.DOCKERFILE)
        - '-t'
        - $(params.IMAGENAME)
        - $(params.CONTEXT)      
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      
    - name: push
      image: $(params.BUILDER_IMAGE)
      command:
        - buildah
        - push
        - '--tls-verify=$(params.TLSVERIFY)'
        - $(params.IMAGENAME)
        - 'docker://$(params.IMAGENAME)'      
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      
  volumes:
    - emptyDir: {}
      name: varlibcontainers
```
