### ISSUE TITLE
argocd-task-sync-and-wait use ARGOCD_AUTH_TOKEN not woring

### ISSUE THREAD

**Issue by lcc3108** [tektoncd/catalog#611]
Hi
I use argocd-task-sync-and-wait whith auth-token.

here is my pipeline
``` yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
spec:
  resources:
    - name: node-web-app-source
      type: git
    - name: node-web-app-image
      type: image
  tasks:
    - name: build-and-publish-image
      resources:
        inputs:
          - name: source
            resource: node-web-app-source
        outputs:
          - name: image
            resource: node-web-app-image
      taskRef:
        kind: Task
        name: source-to-image
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: node-web-app
        - name: flags
          value: '--insecure --grpc-web' # behind proxyy
        - name: argocd-version
          value: v1.7.7 # same as my argocd version
      runAfter:
        - build-and-publish-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
```
An error occurs as shown below.
Server URLs and tokens are hidden for security purposes. 
```
# for debugging printenv
STEP-DEBUG

+ env
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_SERVICE_PORT=443
USER=argocd
EL_NODE_WEB_APP_EL_SERVICE_HOST=10.108.197.186
EL_NODE_WEB_APP_EL_PORT_8080_TCP_ADDR=10.108.197.186
HOSTNAME=node-web-app-pipeline-kgvmq0-argocd-sync-deployment-5qmpt-8bsv2
NODE_WEB_APP_SERVICE_PORT_80_TCP=tcp://10.108.210.68:80
HOME=/tekton/home
EL_NODE_WEB_APP_EL_PORT_8080_TCP_PORT=8080
EL_NODE_WEB_APP_EL_PORT_8080_TCP_PROTO=tcp
ARGOCD_SERVER=argocd.exampl.com
EL_NODE_WEB_APP_EL_SERVICE_PORT=8080
EL_NODE_WEB_APP_EL_PORT=tcp://10.108.197.186:8080
ARGOCD_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZDRmZD
EL_NODE_WEB_APP_EL_PORT_8080_TCP=tcp://10.108.197.186:8080
EL_NODE_WEB_APP_EL_SERVICE_PORT_LISTENER=8080
NODE_WEB_APP_SERVICE_SERVICE_HOST=10.108.210.68
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ARGOCD_OPTS=--grpc-web
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
NODE_WEB_APP_SERVICE_PORT=tcp://10.108.210.68:80
NODE_WEB_APP_SERVICE_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT_HTTPS=443
NODE_WEB_APP_SERVICE_PORT_80_TCP_ADDR=10.108.210.68
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_SERVICE_HOST=10.96.0.1
PWD=/workspace
NODE_WEB_APP_SERVICE_PORT_80_TCP_PORT=80
NODE_WEB_APP_SERVICE_PORT_80_TCP_PROTO=tcp

STEP-LOGIN

+ [ -z eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZD ]

STEP-SYNC

+ argocd app sync node-web-app --revision HEAD --insecure --grpc-web
time="2021-01-05T23:04:13Z" level=fatal msg="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"

STEP-WAIT

2021/01/05 23:04:14 Skipping step because a previous step failed
```
change task use --auth-token flag like beleow now working
``` yaml
# ... skip
  steps:
    - image: 'docker.io/argoproj/argocd:$(params.argocd-version)'
      name: login
      resources: {}
      script: |
        if [ -z $ARGOCD_AUTH_TOKEN ]; then
          yes | argocd login $ARGOCD_SERVER --username=$ARGOCD_USERNAME --password=$ARGOCD_PASSWORD;
        fi
    - image: 'docker.io/argoproj/argocd:$(params.argocd-version)'
      name: sync
      resources: {}
      script: >
        argocd app sync $(params.application-name) --revision $(params.revision)
        $(params.flags) --auth-token $ARGOCD_AUTH_TOKEN
    - image: 'docker.io/argoproj/argocd:$(params.argocd-version)'
      name: wait
      resources: {}
      script: >
        argocd app wait $(params.application-name) --health $(params.flags)
        --auth-token $ARGOCD_AUTH_TOKEN
```
```
STEP-DEBUG

+ env
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
USER=argocd
EL_NODE_WEB_APP_EL_PORT_8080_TCP_ADDR=10.108.197.186
EL_NODE_WEB_APP_EL_SERVICE_HOST=10.108.197.186
HOSTNAME=node-web-app-pipeline-osigcu-argocd-sync-deployment-bfc2b-2qkjb
NODE_WEB_APP_SERVICE_PORT_80_TCP=tcp://10.108.210.68:80
HOME=/tekton/home
EL_NODE_WEB_APP_EL_PORT_8080_TCP_PORT=8080
EL_NODE_WEB_APP_EL_PORT_8080_TCP_PROTO=tcp
ARGOCD_SERVER=argocd.example.com
EL_NODE_WEB_APP_EL_SERVICE_PORT=8080
EL_NODE_WEB_APP_EL_PORT=tcp://10.108.197.186:8080
ARGOCD_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZDRmZD
EL_NODE_WEB_APP_EL_PORT_8080_TCP=tcp://10.108.197.186:8080
EL_NODE_WEB_APP_EL_SERVICE_PORT_LISTENER=8080
NODE_WEB_APP_SERVICE_SERVICE_HOST=10.108.210.68
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ARGOCD_OPTS=--grpc-web
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
NODE_WEB_APP_SERVICE_PORT=tcp://10.108.210.68:80
NODE_WEB_APP_SERVICE_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT_HTTPS=443
NODE_WEB_APP_SERVICE_PORT_80_TCP_ADDR=10.108.210.68
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_SERVICE_HOST=10.96.0.1
PWD=/workspace
NODE_WEB_APP_SERVICE_PORT_80_TCP_PORT=80
NODE_WEB_APP_SERVICE_PORT_80_TCP_PROTO=tcp

STEP-LOGIN

+ [ -z eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZDRmZD ]

STEP-SYNC

+ argocd app sync node-web-app --revision HEAD --insecure --grpc-web --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZDRmZD
TIMESTAMP GROUP KIND NAMESPACE NAME STATUS HEALTH HOOK MESSAGE
2021-01-05T23:15:53+00:00 ConfigMap node-web-project node-web-app-config Synced
2021-01-05T23:15:53+00:00 Service node-web-project node-web-app-service Synced Healthy
2021-01-05T23:15:53+00:00 apps Deployment node-web-project node-web-app-deployment OutOfSync Degraded
2021-01-05T23:15:54+00:00 ConfigMap node-web-project node-web-app-config Synced configmap/node-web-app-config unchanged
2021-01-05T23:15:54+00:00 Service node-web-project node-web-app-service Synced Healthy service/node-web-app-service unchanged
2021-01-05T23:15:54+00:00 apps Deployment node-web-project node-web-app-deployment OutOfSync Degraded deployment.apps/node-web-app-deployment unchanged
Name: node-web-app
Project: default
Server: https://kubernetes.default.svc
Namespace: node-web-project
URL: https://argocd.example.com/applications/node-web-app
Repo: https://github.com/lcc3108/node-web-app
Target: remove-openshift-entity
Path: deployment
SyncWindow: Sync Allowed
Sync Policy: <none>
Sync Status: OutOfSync from remove-openshift-entity (1634e55)
Health Status: Degraded
Operation: Sync
Sync Revision: 545e4adb0d61b21fc8225ef5087b47204f2063a6
Phase: Succeeded
Start: 2021-01-05 23:15:53 +0000 UTC
Finished: 2021-01-05 23:15:54 +0000 UTC
Duration: 1s
Message: successfully synced (all tasks run)
GROUP KIND NAMESPACE NAME STATUS HEALTH HOOK MESSAGE
ConfigMap node-web-project node-web-app-config Synced configmap/node-web-app-config unchanged
Service node-web-project node-web-app-service Synced Healthy service/node-web-app-service unchanged
apps Deployment node-web-project node-web-app-deployment OutOfSync Degraded deployment.apps/node-web-app-deployment unchanged

STEP-WAIT

+ argocd app wait node-web-app --health --insecure --grpc-web --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZTQwMTNkMy01NWJjLTQ1YzAtYTViNy04ZDRmZD
TIMESTAMP GROUP KIND NAMESPACE NAME STATUS HEALTH HOOK MESSAGE
2021-01-05T23:15:56+00:00 apps Deployment node-web-project node-web-app-deployment OutOfSync Degraded deployment.apps/node-web-app-deployment unchanged
2021-01-05T23:15:56+00:00 ConfigMap node-web-project node-web-app-config Synced configmap/node-web-app-config unchanged
2021-01-05T23:15:56+00:00 Service node-web-project node-web-app-service Synced Healthy service/node-web-app-service unchanged
2021-01-05T23:18:42+00:00 apps Deployment node-web-project node-web-app-deployment OutOfSync Degraded deployment.apps/node-web-app-deployment configured
2021-01-05T23:18:42+00:00 apps Deployment node-web-project node-web-app-deployment Synced Progressing deployment.apps/node-web-app-deployment configured
2021-01-05T23:20:17+00:00 apps Deployment node-web-project node-web-app-deployment OutOfSync Progressing deployment.apps/node-web-app-deployment configured
```

I tested the same environment variable locally but there was no error.
I think this bug occurs in the Tekton environment.
