### ISSUE TITLE
Trying to run task docker-build

### ISSUE THREAD

**Issue by johnlongo** [tektoncd/catalog#628]
Trying to run task docker-build, but getting the following error:
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?

Below is the task run I ran, should I be using a different docker.io image than the default already defined?
Please advise and Thank You in advance.

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: docker-open-liberty-pet-store-run
spec:
  params:
  - name: image
    value: image-registry.openshift-image-registry.svc:5000/open-liberty-pet-store/open-liberty-pet-store:latest
  - name: context 
    value: .
  - name: dockerfile
    value: open-liberty-pet-store/Dockerfile
  taskRef:
    name: docker-build
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: maven-source-pvc

**Comment by lbernick** [comment]
/reopen

I am also running into this issue with the following pipeline:

```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  workspaces:
  - name: source-code
  tasks:
  - name: clone
    taskRef:
      name: git-clone
      bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.6
    workspaces:
    - name: output
      workspace: source-code
    params:
    - name: url
      value: https://github.com/lbernick/web-app-demo
  - name: build
    taskRef:
      name: docker-build
      bundle: gcr.io/tekton-releases/catalog/upstream/docker-build:0.1
    workspaces:
    - name: source
      workspace: source-code
    params:
    - name: image
      value: gcr.io/leebernick-test/web-app-demo
    runAfter:
    - clone
```

```
$ tkn pr describe build-and-push-run -n codelab
Name:              build-and-push-run
Namespace:         codelab
Pipeline Ref:      build-and-push
Service Account:   default
Timeout:           1h0m0s
Labels:
 tekton.dev/pipeline=build-and-push

🌡️  Status

STARTED          DURATION     STATUS
40 seconds ago   30 seconds   Failed

💌 Message

Tasks Completed: 2 (Failed: 1, Cancelled 0), Skipped: 0 ("step-docker-build" exited with code 1 (image: "docker-pullable://docker@sha256:18ff92d3d31725b53fa6633d60bed323effb6d5d4588be7b547078d384e0d4bf"); for logs run: kubectl -n codelab logs build-and-push-run-build-pod -c step-docker-build
)

📦 Resources

 No resources

⚓ Params

 No params

📝 Results

 No results

📂 Workspaces

 NAME            SUB PATH   WORKSPACE BINDING
 ∙ source-code   ---        VolumeClaimTemplate

🗂  Taskruns

 NAME                         TASK NAME   STARTED          DURATION     STATUS
 ∙ build-and-push-run-build   build       22 seconds ago   12 seconds   Failed
 ∙ build-and-push-run-clone   clone       40 seconds ago   17 seconds   Succeeded

⏭️  Skipped Tasks

 No Skipped Tasks
```

logs:
```
$ kubectl -n codelab logs build-and-push-run-build-pod -c step-docker-build
Cannot connect to the Docker daemon at tcp://localhost:2376. Is the docker daemon running?
```

tekton version:
```
$ tkn version
Client version: 0.21.0
Pipeline version: devel
Triggers version: v0.17.1
```

k8s version:
```
$ k version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1503", GitCommit:"2c7bbda09a9b7ca78db230e099cf90fe901d3df8", GitTreeState:"clean", BuildDate:"2022-02-18T03:17:45Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

Any owners of this task know what's up? @vdemeester @imjasonh @PuneetPunamiya @popcor255 ?
If I'm using incorrectly happy to update docs!
