### ISSUE TITLE
Extend buildah task with proxy settings

### ISSUE THREAD

**Issue by chrira** [tektoncd/catalog#805]
# Expected Behavior

The buildah task has proxy params like the git-clone task.

```yaml
    - name: httpProxy
      description: git HTTP proxy server for non-SSL requests
      type: string
      default: ""
    - name: httpsProxy
      description: git HTTPS proxy server for SSL requests
      type: string
      default: ""
    - name: noProxy
      description: git no proxy - opt out of proxying HTTP/HTTPS requests
      type: string
      default: ""
```

The proxy params are added to every step as env variables.
E.g with a step template:
```yaml
  stepTemplate:
    env:
    - name: HTTP_PROXY
      value: $(params.HTTP_PROXY)
    - name: HTTPS_PROXY
      value: $(params.HTTPS_PROXY)
    - name: NO_PROXY
      value: $(params.NO_PROXY)
```

# Actual Behavior

Not possible to use the buildah task inside a cluster that is behind a proxy.
I'm not sure if I could use the params BUILD_EXTRA_ARGS and PUSH_EXTRA_ARGS to provide the proxy settings.

# Steps to Reproduce the Problem

Run the buildah task inside a cluster that is behind a proxy.
This means that the container registry is only accessible through a proxy.

# Additional Info

To add a PR I would copy the buildah 0.2 task, rename it to 0.3, add the params and stepTemplate and add tests?
