### ISSUE TITLE
[request] please support non privileged 

### ISSUE THREAD

**Issue by jr00n** [tektoncd/catalog#85]
I'm not allowed by the cluster-admin to add scc privileged to an service account. 
What can I do to make an s2i build like I used to do in Jenkins with a OpenShift builder

**Comment by caggles** [comment]
I read the article posted by @chmouel and it's very interesting, but it says that you can run `buildah unshared` and therefore don't need privileged access - does that case not work for the s2i task for some reason?

**Comment by R-Lam** [comment]
Sorry to revive this but we face this issue the last week after upgrading and the workaround included on the documentation for the downstream version on Openshift help (use vfs as storage driver), but, still needed to include the format for the image to push as docker since the new format is not compatible with some older versions of external registries where we wanted to backup images.

The relevant buildah steps of the task looks like this after the change:

```yaml
- script: |
        [[ "$(workspaces.sslcertdir.bound)" == "true" ]] && CERT_DIR_FLAG="--cert-dir $(workspaces.sslcertdir.path)"
        buildah ${CERT_DIR_FLAG} bud --storage-driver=vfs --tls-verify=$(params.TLSVERIFY) --layers \
        -f /gen-source/Dockerfile.gen -t $(params.IMAGE_NAME) .
  image: quay.io/buildah/stable:v1.17.0
  name: build
  resources:
  limits:
    cpu: '4'
    memory: 4Gi
  requests:
    memory: 4Gi
  volumeMounts:
    - mountPath: /var/lib/containers
       name: varlibcontainers
    - mountPath: /gen-source
       name: gen-source
  workingDir: /gen-source
- script: |
      [[ "$(workspaces.sslcertdir.bound)" == "true" ]] && CERT_DIR_FLAG="--cert-dir $(workspaces.sslcertdir.path)"
      buildah ${CERT_DIR_FLAG} push --storage-driver=vfs --format=docker --tls-verify=$(params.TLSVERIFY) --digestfile $(workspaces.source.path)/image-digest \
        $(params.IMAGE_NAME) docker://$(params.IMAGE_NAME)
  image: quay.io/buildah/stable:v1.17.0
  name: push
  resources: {}
  volumeMounts:
    - mountPath: /var/lib/containers
       name: varlibcontainers
```

Hope this can be helpful for anyone looking to use s2i task without permissions to add scc privileged.
