### ISSUE TITLE
Call Sonar Task with Sonar Arguments

### ISSUE THREAD

**Issue by sanski** [tektoncd/catalog#882]
# Expected / Requestes Behavior
Make an additional paramater in the sonar task to pass all sonar arguments https://docs.sonarqube.org/latest/analysis/analysis-parameters/ to the sonar task.

# Actual Behavior
Current behaviour allows you to either use a full sonar.properties file or pass only two arguments: projectKey and host.url.
This is fine in case the sonar properties are fixed for all pipeline, all repositories and all features, but sometimes you want to change some sonar settings, like the source or tests folder, the sonar wait argument, the verbosity, debug level, language or projectversion.

# Steps to Reproduce the Problem
There is no problem to reproduce, this is just an additional parameter to make the sonar task more flexible.

# Additional Info
Proposed additional argument. Example call in the pipeline:

```
- name: sonar
      taskRef:
        name: custom-sonarqube-scanner
      runAfter:
        - pytest
        - pylint
      params:
        - name: SONAR_HOST_URL
          value: $(params.sonarUrl)
        - name: SONAR_PROJECT_KEY
          value: $(params.sonarProjectName)
        - name: SONAR_ARGS
          value: -Dsonar.projectVersion=$(context.pipelineRun.name) -Dsonar.sources=$(params.sourceDirectory) -Dsonar.tests=$(params.testDirectory) -Dsonar.qualitygate.wait
      workspaces:
        - name: source-dir
          workspace: shared-workspace
        - name: sonar-settings
          workspace: sonar-workspace
```
