### ISSUE TITLE
Update Kaniko Task to work with Chains

### ISSUE THREAD

**Issue by pxp928** [tektoncd/catalog#908]
# Expected Behavior
Kaniko task should be updated to include:

```
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  - name: IMAGE_URL
    description: URL of the image just built.
```
This will allow for chains to sign and add attestation to the image that is created by Kaniko 

# Actual Behavior

Currently Kaniko task in the catalog does not work with chains and the image created is not signed by chains.

# Steps to Reproduce the Problem

1. Running the current Kaniko task with chains running does not sign the image.
