### ISSUE TITLE
cannot run npm build

### ISSUE THREAD

**Issue by chtourou-youssef** [tektoncd/catalog#926]
# Expected Behavior

# Actual Behavior

when using, this template https://hub.tekton.dev/tekton/task/npm , cannot send **" run build "** as args to npm command  and the task is failed

this is the error : 

```
Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /tekton/home/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.7.0 /usr/local/lib/node_modules/npm

Did you mean this?
    rebuild
Step failed
```

# Additional Info

**Comment by vinamra28** [comment]
@chtourou-youssef thanks for creating the issue. If possible can please share how you are sending your args to the Task? Also to cross-check does your package.json contains respective `build` script?

**Comment by chtourou-youssef** [comment]
@vinamra28 ; thanks for your reply,
This is the package.json : 
```
{
  "name": "XXXXXXXX",
  "version": "XXXXXXX",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },

```
I use the same task in the tekton hub documentation. 
you find bellow the link : https://hub.tekton.dev/tekton/task/npm.

In my local machine, **npm run build** work as excecpted and a **dist** folder is generated.

this is my pipeline : 

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-angular-project
spec:
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
      - name: install-dependencies
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - install
        runAfter:
          - fetch-repository
      - name: show-version
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value: 
              - version
        runAfter:
          - install-dependencies
      - name: test-project
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - test
        runAfter:
          - show-version
      - name: build-project
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - run build
        runAfter:
          - show-version

      - name: list-project
        taskRef:
          name: command
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - build-project
```

**Comment by vinamra28** [comment]
@chtourou-youssef can you please try the below?
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-push-angular-project
spec:
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  pipelineSpec:
    workspaces:
      - name: shared-workspace
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-workspace
        params:
          - name: url
            value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          - name: subdirectory
            value: ""
          - name: deleteExisting
            value: "true"
      - name: install-dependencies
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - install
        runAfter:
          - fetch-repository
      - name: show-version
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value: 
              - version
        runAfter:
          - install-dependencies
      - name: test-project
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - test
        runAfter:
          - show-version
      - name: build-project
        taskRef:
          name: npm-build
        workspaces:
          - name: source
            workspace: shared-workspace
        params:
          - name: PATH_CONTEXT
            value: "."
          - name: ARGS
            value:
              - run
              - build
        runAfter:
          - show-version

      - name: list-project
        taskRef:
          name: command
        workspaces:
          - name: source
            workspace: shared-workspace
        runAfter:
          - build-project
```
