### ISSUE TITLE
Kaniko unable to authenticate

### ISSUE THREAD

**Issue by WLun001** [tektoncd/catalog#931]
# Expected Behavior
Kaniko authenticated successfully

# Actual Behavior
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "[ghcr.io/username/hello-world](http://ghcr.io/wlun001/hello-world)": POST https://ghcr.io/v2/username/hello-world/blobs/uploads/: DENIED: unauthenticated: User cannot be authenticated with the token provided.
```

# Steps to Reproduce the Problem

1. write pipeline
2. write pipelinerun

```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
spec:
  workspaces:
    - name: git-source
    - name: dockerconfig
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/username/repo
      workspaces:
        - name: output
          workspace: git-source
    - name: build-image
      runAfter: [fetch-from-git]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: ghcr.io/username/hello-world
        - name: CONTEXT
          value: examples/hello-world
        - name: DOCKERFILE
          value: $(workspaces.source.path)/examples/hello-world/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
        - name: dockerconfig
          workspace: dockerconfig
```
```yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-pipeline-run-
spec:
  pipelineRef:
    name: kaniko-pipeline
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 100m
    - name: dockerconfig
      secret:
        secretName: regcred

```

# Additional Info
The credentials are all correct, able to push to registry from local `docker` cli
