### ISSUE TITLE
Update jib-grade task to work with Chains

### ISSUE THREAD

**Issue by bradbeck** [tektoncd/catalog#946]
# Expected Behavior
`jib-gradle` task should be updated to include `IMAGE_URL` in its results:
```yaml
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  - name: IMAGE_URL
    description: URL of the image just built.
```
This will allow Chains to sign and add an attestation to the image by `jib-gradle`

# Actual Behavior
Currently the `jib-gradle` task in the catalog does not work with Chains and the image created is not signed by Chains.

# Steps to Reproduce the Problem

1. Running the current `jib-gradle` task with Chains, the image created is not signed by Chains
